name: Deploy to Production

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 5"

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: Production
    env:
      GCP_IMAGE: ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud 🔐
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup Google Cloud ⚙️
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Authorize Docker push 🚢
        run: gcloud auth configure-docker

      - name: Build and push image 🏗
        run: |-
          docker build -t gcr.io/${{ env.GCP_IMAGE }} .
          docker push gcr.io/${{ env.GCP_IMAGE }}

      - name: Deploy 🚀
        uses: google-github-actions/deploy-cloudrun@v0.9.0
        with:
          service: ${{ secrets.GCP_SERVICE_NAME }}
          image: gcr.io/${{ env.GCP_IMAGE }}
          region: ${{ secrets.GCP_REGION }}
